#!/usr/bin/env bash
#
# Converts assertion failure text involving two mutations to a diff.
#
# Usage: mutation_diff <path-to-test-output-file>
#

function transform() {
    # Continuity is ignored by equality
    #sed 's/cont=[[:alpha:]]*/cont=\*/g'
    cat
}

colordiff -u <(sed -n '/expected\|t match/,/got:\|and:/p' $1 | head -n-1 | transform) \
             <(sed -n '/got:\|and:/,/^$/p' $1 | transform) | less -R
