# Interface of the scylla_test module embedded in the pyunit runner
# (test/pyunit/runner.cc). Not importable under plain python3; exists for
# IDE support and as the binding contract.
#
# Mapping to C++:
#   Env                    -> cql_test_env (test/lib/cql_test_env.hh)
#   TopologyBuilder        -> topology_builder (test/lib/topology_builder.hh)
#   TabletMap              -> staged locator::tablet_map content
#   LoadSketch             -> eager snapshot of locator::load_sketch
#   update_tablet_metadata -> mutate_tablets() from tablets_test.cc
#   rebalance_tablets      -> rebalance_tablets() from tablets_test.cc
#
# Threading model: each call crosses to the seastar reactor via
# seastar::alien::submit_to() and blocks (GIL released) until the future
# resolves. Scylla objects stay reactor-side; Python holds handles.

from typing import Optional

class HostId:
    def __str__(self) -> str: ...

class TableId: ...

Replica = tuple[HostId, int]  # (host, shard)

class TabletMap:
    def __init__(self, tablet_count: int) -> None: ...
    def __setitem__(self, tablet_index: int, replicas: list[Replica]) -> None: ...
    def __len__(self) -> int: ...

class TabletMetadataUpdate:
    def __setitem__(self, table: TableId, tmap: TabletMap) -> None: ...
    def __enter__(self) -> "TabletMetadataUpdate": ...
    def __exit__(self, *exc) -> bool: ...

class LoadSketch:
    def tablet_count(self, host: HostId) -> float: ...
    def avg_tablet_count(self, host: HostId) -> int: ...

class LoadStats:
    def set_default_tablet_sizes(self) -> None: ...

class TopologyBuilder:
    dc: str
    load_stats: LoadStats
    def add_node(self, shards: int = 1) -> HostId: ...

class Env:
    def execute(self, cql: str) -> None: ...
    def topology_builder(self) -> TopologyBuilder: ...
    def add_keyspace(self, rf: dict[str, int], initial_tablets: int = 0) -> str: ...
    def add_table(self, keyspace: str) -> TableId: ...
    def update_tablet_metadata(self) -> TabletMetadataUpdate: ...
    def load_sketch(self) -> LoadSketch: ...
    def rebalance_tablets(self, load_stats: Optional[LoadStats] = None) -> None: ...

def start_env() -> Env: ...
def stop_env() -> None: ...
