# Binding surface implied by test_tablets.py — the contract the pybind11
# module must implement. Scoped to what the first converted test needs;
# grows test by test.
#
# Mapping to C++ (all under test/lib/ and locomotor internals):
#   CqlTestEnv              -> cql_test_env (test/lib/cql_test_env.hh)
#   TopologyBuilder         -> topology_builder (test/lib/topology_builder.hh)
#   TabletMap / replicas    -> locator::tablet_map / tablet_replica_set
#   LoadSketch              -> locator::load_sketch
#   update_tablet_metadata  -> mutate_tablets() with group0_guard
#   rebalance_tablets       -> tablets_test.cc rebalance_tablets() helper
#
# Threading model: each method submits to the seastar reactor via
# seastar::alien::submit_to() and blocks (GIL released) until the future
# resolves. Objects are opaque handles owned reactor-side; Python holds ids.

from contextlib import AbstractContextManager
from enum import Enum
from typing import Iterator

class HostId:
    def __str__(self) -> str: ...

class TableId: ...

class NodeState(Enum):
    normal = ...
    joining = ...
    leaving = ...

Replica = tuple[HostId, int]  # (host, shard)

class TabletMap:
    def __init__(self, tablet_count: int) -> None: ...
    def __setitem__(self, tablet_index: int, replicas: list[Replica]) -> None: ...
    def __getitem__(self, tablet_index: int) -> list[Replica]: ...
    def __len__(self) -> int: ...

class TabletMetadata:
    def __setitem__(self, table: TableId, tmap: TabletMap) -> None: ...
    def __getitem__(self, table: TableId) -> TabletMap: ...

class LoadSketch:
    def tablet_count(self, host: HostId) -> int: ...
    def avg_tablet_count(self, host: HostId) -> float: ...

class LoadStats:
    def set_default_tablet_sizes(self) -> None: ...

class TopologyBuilder:
    dc: str
    load_stats: LoadStats
    def add_node(self, state: NodeState = NodeState.normal, shards: int = 1) -> HostId: ...
    def start_new_rack(self) -> None: ...
    def start_new_dc(self) -> str: ...

class ResultSet:
    def __iter__(self) -> Iterator[tuple]: ...
    def one(self) -> tuple: ...

class CqlTestEnv:
    def execute(self, cql: str, *args) -> ResultSet: ...
    def topology_builder(self) -> TopologyBuilder: ...
    def add_keyspace(self, rf: dict[str, int], initial_tablets: int) -> str: ...
    def add_table(self, keyspace: str) -> TableId: ...
    def update_tablet_metadata(self) -> AbstractContextManager[TabletMetadata]: ...
    def load_sketch(self) -> LoadSketch: ...
    def rebalance_tablets(self, load_stats: LoadStats | None = None) -> None: ...
